ZOMBIE:
  allowedWorlds:
    - world
  commandWithChances:
    - amount: 1
      chance: 90.0
      displayName: "&0[&e&lTokens&0] &eVoucher"
      displayLore:
        - "&f100 Tokens"
      command: "tgive {player} 100"
      redeemMessage: "&eYou have redeemed 100 tokens"
      displayMaterial: PAPER
